docs: update README for debugging components
saigontechnology/rn-base-component pull request #22
Opened 2023-03-29 11:56 UTC by baonguyenhsts

2023-03-30 02:22 UTC, ngochuyduong requested changes

2023-03-30 02:22 UTC, ngochuyduong commented on README.md
> +```sh
Add yarn command.

```sh
yarn
yarn bootstrap
yarn ios/android
```

2023-03-31 09:17 UTC, huydosgtech commented
- move to example folder template

2023-04-05 02:10 UTC, ngochuyduong approved these changes

2023-04-07 07:02 UTC, TranQuangPhi approved these changes

2023-04-10 08:22 UTC, merged