fix: button style
saigontechnology/rn-base-component pull request #72
Opened 2023-11-16 07:37 UTC by ZanBin

## Summary

## Features

## Bugs

## Check List
- [ ] Your code builds clean without any errors or warnings.
- [ ] Check coding convention.
- [ ] Updated Storybook components and stories to reflect any changes made to the UI.
- [ ] Test covers all edge cases and coverage is greater than or equal to 80%.

## Proof of Completeness
<img alt="Screenshot changes introduced" src="<uploaded_image_url>" width="250" />
OR
Video link

2023-11-17 09:00 UTC, loc-nguyenthien requested changes

2023-11-21 07:35 UTC, loc-nguyenthien approved these changes

2023-11-21 08:34 UTC, honghoangsts requested changes

2023-11-21 08:34 UTC, honghoangsts commented on src/components/Button/Button.tsx
> +    fontSize: textSize ? textSize : metrics.xs,
`textSize ?? metrics.xs`

2023-11-21 08:39 UTC, honghoangsts approved these changes

2023-11-22 09:42 UTC, honghoangsts approved these changes

2023-11-22 09:42 UTC, merged