Fix/wrong styled component
saigontechnology/rn-base-component pull request #76
Opened 2023-11-21 16:00 UTC by huydosgtech

## Summary

## Features

## Bugs

## Check List
- [ ] Your code builds clean without any errors or warnings.
- [ ] Check coding convention.
- [ ] Updated Storybook components and stories to reflect any changes made to the UI.
- [ ] Test covers all edge cases and coverage is greater than or equal to 80%.

## Proof of Completeness
<img alt="Screenshot changes introduced" src="<uploaded_image_url>" width="250" />
OR
Video link

2023-11-22 01:42 UTC, hangnguyensaigontech approved these changes

2023-11-22 10:03 UTC, baonguyenhsts requested changes

2023-11-22 10:03 UTC, baonguyenhsts commented on src/components/Checkbox/Checkbox.tsx
>    theme?: ITheme
remove this prop

2023-11-22 10:03 UTC, baonguyenhsts commented on src/components/Checkbox/Checkbox.tsx
>    theme?: ITheme
remove this prop

2023-11-22 10:03 UTC, baonguyenhsts commented on src/components/Checkbox/Checkbox.tsx
>    theme?: ITheme
Please check and remove all `theme?: ITheme`

2023-11-22 12:30 UTC, honghoangsts requested changes

2023-11-23 02:46 UTC, ledutu2 approved these changes

2023-11-23 03:48 UTC, honghoangsts approved these changes

2023-11-23 03:54 UTC, merged